# Generated by Django 4.2.1 on 2023-06-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_link',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
